import { createReadStream } from 'node:fs'
import { mkdir, open, realpath, rm } from 'node:fs/promises'
import { dirname, resolve, sep } from 'node:path'
import type { Readable } from 'node:stream'

/** Storage abstraction (ARCHITECTURE §15). The database holds metadata and the key; never the bytes. */
export interface StorageDriver {
  /** Creates the object; never overwrites an existing one (rejects instead). */
  put(key: string, bytes: Uint8Array): Promise<void>
  /** Rejects with `StorageObjectNotFoundError` when the object does not exist. */
  get(key: string): Promise<Readable>
  exists(key: string): Promise<boolean>
  /** Idempotent: deleting a missing object succeeds. */
  delete(key: string): Promise<void>
}

export class InvalidStorageKeyError extends Error {
  constructor(key: string) {
    // The key is echoed (JSON-quoted, so control characters stay visible and harmless) for diagnostics;
    // it is server-generated and never reaches an HTTP response.
    super(`Invalid storage key: ${JSON.stringify(key)}`)
    this.name = 'InvalidStorageKeyError'
  }
}

export class StorageObjectNotFoundError extends Error {
  constructor() {
    super('Storage object not found')
    this.name = 'StorageObjectNotFoundError'
  }
}

const MAX_KEY_LENGTH = 512
/** A directory segment of a key: ASCII letters, digits, `_` and `-` only (no dots, spaces, separators, NUL). */
const DIR_SEGMENT = /^[A-Za-z0-9_-]+$/
/** The last segment: a name plus exactly one lowercase extension. */
const FILE_SEGMENT = /^[A-Za-z0-9_-]+\.[a-z0-9]{2,5}$/

/** Pure key check, exported for tests: `dir/dir/name.ext` (any number of directories), no empty segments, no dots but the extension's. */
export function isValidStorageKey(key: unknown): key is string {
  if (typeof key !== 'string' || key.length === 0 || key.length > MAX_KEY_LENGTH) return false
  const segments = key.split('/')
  const file = segments.pop()!
  return FILE_SEGMENT.test(file) && segments.every(s => DIR_SEGMENT.test(s))
}

function isMissing(error: unknown): boolean {
  const code = (error as { code?: unknown } | null)?.code
  return code === 'ENOENT' || code === 'ENOTDIR'
}

export class LocalStorageDriver implements StorageDriver {
  private readonly root: string

  constructor(rootDir: string) {
    this.root = resolve(rootDir)
  }

  /**
   * Keys are generated by the server (`<orgId>/<yyyy>/<uuid>.<ext>`); this still refuses anything
   * else: traversal, absolute paths, separators other than `/`, empty segments, NUL, spaces. The
   * resolved path must also stay strictly below the root (belt and braces over the key grammar).
   */
  private pathFor(key: string): string {
    if (!isValidStorageKey(key)) throw new InvalidStorageKeyError(key)
    const full = resolve(this.root, key)
    if (!full.startsWith(this.root + sep)) throw new InvalidStorageKeyError(key)
    return full
  }

  /** `real` (a realpath) must lie strictly below the root's own realpath — a symlink inside the tree cannot lead out of it. */
  private assertBelowRoot(realRoot: string, real: string, key: string): void {
    if (!real.startsWith(realRoot + sep)) throw new InvalidStorageKeyError(key)
  }

  /** The existing object's real path, or null when it does not exist. Throws for a symlink escaping the root. */
  private async existingPath(key: string): Promise<string | null> {
    const full = this.pathFor(key)
    let realRoot: string
    let real: string
    try {
      realRoot = await realpath(this.root)
      real = await realpath(full)
    }
    catch (error) {
      if (isMissing(error)) return null
      throw error
    }
    this.assertBelowRoot(realRoot, real, key)
    return real
  }

  async put(key: string, bytes: Uint8Array) {
    const path = this.pathFor(key)
    await mkdir(dirname(path), { recursive: true })
    // A symlinked directory inside the root must not redirect the write outside it.
    this.assertBelowRoot(await realpath(this.root), await realpath(dirname(path)), key)
    // 'wx' = O_CREAT | O_EXCL: fails with EEXIST if anything (a file, or a symlink — even a dangling one) is there.
    const handle = await open(path, 'wx')
    try {
      await handle.writeFile(bytes)
    }
    catch (error) {
      // The object was created by this call and is incomplete: remove it so no partial file remains.
      await handle.close().catch(() => undefined)
      await rm(path, { force: true }).catch(() => undefined)
      throw error
    }
    await handle.close()
  }

  async get(key: string) {
    const path = await this.existingPath(key)
    if (path === null) throw new StorageObjectNotFoundError()
    return createReadStream(path)
  }

  async exists(key: string) {
    return (await this.existingPath(key)) !== null
  }

  async delete(key: string) {
    const path = await this.existingPath(key)
    if (path !== null) await rm(path, { force: true })
  }
}
